# Exported from:        http://Alens-MacBook-Air.local:5516/
# Release version:      24.1.0
# Date created:         Mon Oct 13 15:22:14 CEST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Apps and Envs
spec:
- template: B
  scheduledStartDate: 2025-10-13T09:00:00+02:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
  author: admin
