# Exported from:        http://Alens-MacBook-Air.local:5516/
# Release version:      24.1.0

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ImportError
spec:
- template: Placeholder
  scheduledStartDate: 2026-01-15T09:00:00+01:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
  author: admin
