# Exported from:        http://Alens-MacBook-Air.local:5516/
# Release version:      24.1.0
# Date created:         Fri Oct 03 13:50:14 CEST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Apps and Envs
spec:
- template: Demo
  scheduledStartDate: 2025-09-30T09:00:00+02:00
  dueDate: 2025-09-30T10:00:00+02:00
  phases:
  - phase: New Phase
    tasks:
    - name: M1
      type: xlrelease.Task
      facets:
      - type: udm.DeploymentTaskFacet
        variableMapping:
          environmentId: "${env1}"
        version: "1.00"
        application: App 1
  variables:
  - type: xlrelease.StringVariable
    key: env1
    value: Env 1
  riskProfile: Default risk profile
  author: admin
